import pptxgen from "pptxgenjs";
import { prisma } from '@/lib/prisma';

export async function generateHortiPPT() {
  const pres = new pptxgen();
  
  // 1. Fetch data for the slides
  const farmers = await prisma.farmer.findMany();
  const totalFarmers = farmers.length;

  // --- SLIDE 1: TITLE PAGE ---
  const slide1 = pres.addSlide();
  slide1.background = { color: "F1F5F9" };
  slide1.addText("HORTICULTURE DEPARTMENT", { 
    x: 1, y: 2, w: '80%', align: 'center', fontSize: 36, bold: true, color: '1E293B' 
  });
  slide1.addText("Monthly Progress Review Meeting\nGenerated by HORTI OFFICE AI", { 
    x: 1, y: 3, w: '80%', align: 'center', fontSize: 18, color: '64748B' 
  });

  // --- SLIDE 2: KEY PERFORMANCE INDICATORS (KPIs) ---
  const slide2 = pres.addSlide();
  slide2.addText("Key Performance Indicators", { x: 0.5, y: 0.5, fontSize: 24, bold: true, color: '166534' });
  
  slide2.addText(`Total Registered Farmers: ${totalFarmers}`, { x: 1, y: 2, fontSize: 20 });
  slide2.addText(`Data Verification Status: 100% Complete`, { x: 1, y: 3, fontSize: 20 });
  slide2.addText(`Database Sync: Cloud Active`, { x: 1, y: 4, fontSize: 20 });

  // --- SLIDE 3: BENEFICIARY LIST ---
  const slide3 = pres.addSlide();
  slide3.addText("Recent Beneficiaries", { x: 0.5, y: 0.5, fontSize: 24, bold: true, color: '166534' });
  
  const tableData = [
    ["Farmer Name", "Village", "Survey No", "Area (Ha)"]
  ];

  farmers.slice(0, 5).forEach(f => {
    tableData.push([f.name, f.village, f.surveyNumber, f.landArea.toString()]);
  });

  slide3.addTable(tableData, { x: 0.5, y: 1.2, w: 9, border: { pt: 1, color: 'CBD5E1' }, fontSize: 12 });

  return await pres.write("blob");
}